document.addEventListener('DOMContentLoaded',()=>{
  const search=document.querySelector('#news-search'),filters=[...document.querySelectorAll('.filter')],items=[...document.querySelectorAll('.searchable')],empty=document.querySelector('#empty-state');let active='all';
  const apply=()=>{const q=(search?.value||'').trim().toLowerCase();let shown=0;items.forEach(item=>{const cats=(item.dataset.category||'').split(/\s+/),text=(item.dataset.search||item.textContent||'').toLowerCase(),ok=(active==='all'||cats.includes(active))&&(!q||text.includes(q));item.hidden=!ok;if(ok)shown++;});if(empty)empty.hidden=shown!==0;};
  filters.forEach(btn=>btn.addEventListener('click',()=>{active=btn.dataset.filter||'all';filters.forEach(x=>x.classList.toggle('is-active',x===btn));apply();}));search?.addEventListener('input',apply);
  const src=(label,name,url)=>`<div class="analysis-source-row"><span>${label}</span><a href="${url}" target="_blank" rel="noreferrer">${name} ↗</a></div>`;
  const data=[
    {keys:['Tripo P2.0','Native Quad'],week:`<h4>本週發生什麼變化</h4><p>Tripo P2.0 Preview 把 AI 3D 的競爭從外觀品質推向 Native Quad 與更高 mesh budget。相較本週前段仍偏生成與 reference control 的討論，現在開始直接碰 Retopo、Rig 與 Animation handoff。</p><h4>Production 趨勢</h4><p>AI 3D 的價值判斷正在從「生成得像不像」轉成「生成後能少做多少 Cleanup」。四邊面本身不是終點，肩、胯、膝、眼口的 deformation edge flow 才是角色 Production 的真正門檻。</p><h4>本週判斷</h4><p>值得立即小規模實測，不建議直接取代人工 Retopo。先用已有人工答案的人形或生物做 A/B，若局部修線時間能少一半以上才有導入價值。</p>${src('來源／可信度','Tripo 官方 Blog','https://www.tripo3d.ai/blog')}`,day:`<h4>更新內容</h4><p>P2.0 Preview 主打 Native Quad Topology 與更高 mesh budget，定位直接指向 editing、rigging、animation 與 real-time workflow。它仍是 Preview，因此不能把「Native Quad」直接等同 animation-ready topology。</p><h4>對 3D 美術的影響</h4><p>角色與 Creature 應優先檢查肩、胯、膝、肘、眼口與 pole；Prop 則看洞口、薄片、倒角與硬表面邊界。若只需局部修線，AI → 全部重拓撲才有機會縮成 AI → 局部 Cleanup → UV／Skin。</p><h4>Production 判斷／限制</h4><p>Production ★★★☆☆。潛在節省時間高，但 deformation loop、UV seam 可設性與 subdivision 輪廓仍需人工驗證。適合角色美術、Creature Artist、Rigger、TA、Prop Artist。</p><h4>20 分鐘實測</h4><p>拿已有人工 Low-poly 的角色只看 Wireframe，比肩／胯 loop、pole、眼口 topology、UV seam 與 Subdivision 後輪廓。</p>${src('來源／可信度','Tripo 官方 Blog','https://www.tripo3d.ai/blog')}`},
    {keys:['Meshy 7','Smart Topology'],week:`<h4>本週發生什麼變化</h4><p>Meshy 7、Ultra、Multi-Image texture reference 與 Smart Topology 在本週形成更清楚的分工：高保真 geometry、texture control、低面數 topology 不再被當成同一個步驟。</p><h4>Production 趨勢</h4><p>這代表 AI 資產流程正在模組化。真正應比較的是 Generate → Cleanup → UV／Material → Engine 的總時間，而不是只看第一張 turntable。</p><h4>本週判斷</h4><p>Prop、Background Asset 值得導入測試；deformation character 仍需保守。建議建立固定 4K triangles 與高保真兩條測試線。</p>${src('來源／可信度','Meshy 官方 API Changelog','https://docs.meshy.ai/en/api/changelog')}`,day:`<h4>更新內容</h4><p>Meshy 7 是標準高保真生成模型；Smart Topology 則使用獨立 meshy-t2 流程，可指定 target polycount，官方文件目前標示 100–15,000 triangles。兩者應分開評估。</p><h4>對 3D 美術的影響</h4><p>合理流程是 Meshy 7 做形體／材質 first pass，需要低模時再跑 Smart Topology。對 Prop 與 Background Asset，這比固定全案只用最新模型更接近 Production。</p><h4>Production 判斷／限制</h4><p>Production ★★★☆☆。低面數輸出仍需檢查 UV、Normal、分件、非流形、LOD、Collision；角色 deformation 不應只看 triangle 數就判定可用。</p><h4>20 分鐘實測</h4><p>同一 Prop 做高保真版與 Smart Topology 4K triangles，進 Blender 記錄 silhouette、UV、material slot、normal 與人工修理分鐘數。</p>${src('來源／可信度','Meshy 官方 API Changelog','https://docs.meshy.ai/en/api/changelog')}`},
    {keys:['Spider Walker','程序動畫','先 Live'],week:`<h4>本週發生什麼變化</h4><p>Blender 5.2 生態出現更實際的程序 locomotion 案例：Spider Walker 把多足角色的落腳、地面追蹤與步序變成 live solver，最後再 Bake。</p><h4>Production 趨勢</h4><p>重點不是取代 Animator，而是把重複性的 ground contact first pass 程序化，再把 timing、overlap、secondary motion 留給人工。這種「Live → Validate → Bake」也適合其他 Rig 工具。</p><h4>本週判斷</h4><p>Creature／Robot 專案值得測，導入成本低；一般人形角色則先當輔助技術，不必取代既有 locomotion SOP。</p>${src('來源／可信度','80 Level／作者工具介紹','https://80.lv/articles/free-blender-tool-for-procedural-spider-walks')}`,day:`<h4>核心內容</h4><p>Spider Walker 會依 root motion 預估 foot target，raycast 地面，再依腿序列決定抬腳與落腳；滿意後可 Bake 成一般 Action。</p><h4>對 3D 美術的影響</h4><p>多足怪物、機械蜘蛛與 Boss 可以快速得到 locomotion first pass，Animator 再集中處理節奏、身體重心與 secondary motion。</p><h4>Production 判斷／限制</h4><p>Prototype ★★★★☆。急轉彎可能腿交叉、速度突變可能腳滑，跳躍與跨障礙需要額外狀態。適合 Animator、Rigger、Creature Artist、TA。</p><h4>15 分鐘實測</h4><p>用 4 足 rig 在平地、15° 斜坡與小階梯各走一次，再 Bake，檢查腳滑、交叉與曲線密度。</p>${src('來源／可信度','80 Level／作者工具介紹','https://80.lv/articles/free-blender-tool-for-procedural-spider-walks')}`},
    {keys:['River Modeler','Jobs / Burst','Jobs + Burst'],week:`<h4>本週發生什麼變化</h4><p>Unity 場景工具的訊號從單一 spline authoring 進一步走向 Jobs、Burst、MeshData、segment 與 streaming。河流只是案例，架構可以延伸到道路、管線、電纜與長牆。</p><h4>Production 趨勢</h4><p>大型場景製作正把「美術控制路徑與變化」和「系統負責 mesh generation／streaming」拆開，降低巨大單一 mesh 與手工重建成本。</p><h4>本週判斷</h4><p>若專案已使用 Unity 6／Stylized Water 3，值得建立 baseline 等新版比較；其他專案則先吸收架構，不必為單一工具切換技術棧。</p>${src('來源／可信度','80 Level 技術報導','https://80.lv/articles/unity-s-stylized-water-3-is-getting-spline-based-river-modeler-tool')}`,day:`<h4>核心內容</h4><p>River Modeler 重構方向是 Spline → Segment → MeshData → Jobs/Burst 平行生成，再串 VFX／Audio streaming 與 terrain workflow。作者在部分長 spline case 宣稱最高約 24×。</p><h4>對 3D 美術的影響</h4><p>Environment Artist 可以把時間放在 river path、width、bank 與 material variation，系統處理長距離 mesh 與局部更新。</p><h4>Production 判斷／限制</h4><p>Environment ★★★★☆。架構價值高，但 24× 是作者測試數據，且工具依賴 Unity／Stylized Water 3 生態。適合 Environment Artist、Level Artist、TA。</p><h4>20 分鐘實測</h4><p>先替現有 spline river 建 500m／2km baseline，記錄 editor generation time、物件數與 drawcall，之後與新版 A/B。</p>${src('來源／可信度','80 Level 技術報導','https://80.lv/articles/unity-s-stylized-water-3-is-getting-spline-based-river-modeler-tool')}`},
    {keys:['Stefan','Souls-like'],week:`<h4>本週發生什麼變化</h4><p>Stefan 的 72 小時 Souls-like 案例把 AI 3D 從單一模型比較拉回完整遊戲製作時限：生成只是前段，後面仍有 Cleanup、Collision、Pivot、Scale、Lighting、Animation compatibility 與 Engine assembly。</p><h4>Production 趨勢</h4><p>本週 AI 3D 的共同趨勢都是開始量「總交付時間」而不是生成秒數。這與 Tripo／Meshy 對 topology 與 handoff 的更新形成同一條主線。</p><h4>本週判斷</h4><p>值得當 workflow case study，但影片含工具推廣，不應當獨立 benchmark。最適合拿一個 Prop 複製整條流程並自己計時。</p>${src('來源／可信度','Stefan 3D AI YouTube','https://www.youtube.com/watch?v=9kejfKCb0S8')}`,day:`<h4>核心內容</h4><p>案例的價值是把 AI 資產塞進 72 小時遊戲製作，觀察生成後仍需人工處理的場景 assembly、lighting、collision、角色匯入與 Unreal setup。</p><h4>對 3D 美術的影響</h4><p>評估 AI 工具時應把 Generate、Cleanup、Pivot／Scale、Material、Collision、Engine import 全部計時，避免只看生成速度造成錯誤 ROI。</p><h4>Production 判斷／限制</h4><p>案例價值 ★★★★☆。適合 AI Pipeline 評估者、Indie、Lead、TA；影片含 Tripo 推廣，因此品質結論要用自己的資產再驗證。</p><h4>20 分鐘實測</h4><p>只做一個 Prop：AI 生成 → Blender Cleanup → Collision／Pivot → Unreal import，逐段記錄分鐘數。</p>${src('來源／可信度','Stefan 3D AI YouTube','https://www.youtube.com/watch?v=9kejfKCb0S8')}`}
  ];
  const find=t=>data.find(d=>d.keys.some(k=>t.includes(k)));
  const details=(html,label='完整分析')=>{const d=document.createElement('details');d.className='home-full-analysis';d.innerHTML=`<summary>${label}</summary><div class="home-analysis-body">${html}</div>`;return d;};
  document.querySelectorAll('.week-topic').forEach(card=>{if(card.querySelector('.home-full-analysis'))return;const d=find(card.textContent||'');if(d)card.append(details(d.week));});
  document.querySelectorAll('.top-item').forEach(link=>{if(link.querySelector('.home-full-analysis'))return;const d=find(link.textContent||'');if(!d)return;const article=document.createElement('article');article.className='top-item top-item-expandable';article.innerHTML=link.innerHTML;article.querySelector(':scope > strong')?.remove();article.querySelector(':scope > div')?.append(details(d.day));link.replaceWith(article);});
  document.querySelectorAll('.more-card details').forEach(d=>{d.classList.add('home-full-analysis');d.querySelector('.detail-body')?.classList.add('home-analysis-body');});
  const all=[...document.querySelectorAll('.home-full-analysis')];all.forEach(d=>d.addEventListener('toggle',()=>{if(d.open)all.forEach(o=>{if(o!==d)o.open=false;});}));
});