#!/usr/bin/env python3
from pathlib import Path
from bs4 import BeautifulSoup, Tag

ROOT = Path(__file__).resolve().parents[1]

CASES = [
    {
        'keys': ['Serie 角色案例', 'Serie from Frieren', 'Stylized Take on Serie', 'serie'],
        'asset': 'serie-npr.jpg',
        'label': 'SOURCE COVER',
        'source': 'https://80.lv/articles/stylized-take-on-serie-from-frieren-that-feels-purely-2d'
    },
    {
        'keys': ['Painterly 3D World', '2D Concept → Painterly 3D World', 'Turning 2D Concept Art', 'painterly 3d world'],
        'asset': 'painterly-world.jpg',
        'label': 'SOURCE COVER',
        'source': 'https://80.lv/articles/turning-2d-concept-art-into-a-detailed-painterly-3d-world'
    },
    {
        'keys': ['Headcrab', 'Substrate 材質案例', 'headcrab'],
        'asset': 'headcrab-substrate.jpg',
        'label': 'SOURCE COVER',
        'source': 'https://80.lv/articles/3d-artist-reimagined-half-life-2-s-headcrab-with-unreal-engine-5-s-substrate'
    },
    {
        'keys': ['Painterly Shadows'],
        'asset': 'painterly-shadows.jpg',
        'label': 'SOURCE COVER',
        'source': 'https://studio.blender.org/blog/painterly-shadows/'
    },
]

PREVIEW_CSS = '''\n/* Visual Evidence Preview: local assets generated by scripts/extract_visual_assets.py */\n.case-preview{margin:12px 0 4px;max-width:760px}.case-preview a{display:block;text-decoration:none}.case-preview img{display:block;width:100%;height:auto;max-height:430px;object-fit:contain;border-radius:10px;border:1px solid #29384f;background:#0b1220}.case-preview figcaption{margin-top:6px;color:#8793a8;font-size:.66rem;font-weight:900;letter-spacing:.06em}.case-preview figcaption span{color:#a69cff}.news .case-preview img,.category-news .case-preview img{border-color:#dde2e9;background:#f5f7fa}.news .case-preview figcaption,.category-news .case-preview figcaption{color:#717b89}.news .case-preview figcaption span,.category-news .case-preview figcaption span{color:#6359c9}@media(max-width:760px){.case-preview img{max-height:360px}}\n'''


def matching_case(text):
    low = text.lower()
    for case in CASES:
        if any(k.lower() in low for k in case['keys']):
            return case
    return None


def make_preview(soup, case, asset_prefix):
    fig = soup.new_tag('figure', attrs={'class':'case-preview','data-visual-id':case['asset'].rsplit('.',1)[0]})
    a = soup.new_tag('a', href=case['source'], target='_blank', rel='noreferrer', title='開啟原始案例')
    img = soup.new_tag('img', src=f'{asset_prefix}{case["asset"]}', alt=f'{case["label"]} preview', loading='lazy', decoding='async')
    img['onerror'] = "this.closest('.case-preview').style.display='none'"
    a.append(img); fig.append(a)
    cap = soup.new_tag('figcaption')
    tag = soup.new_tag('span'); tag.string = case['label']
    cap.append(tag); cap.append(' · Local visual evidence · 點圖開啟原始來源')
    fig.append(cap)
    return fig


def remove_no_image_note(article):
    # Remove stale explanatory blocks saying that a preview could not be obtained.
    for h in list(article.find_all(['h4','strong','b'])):
        if 'Visual Evidence' in h.get_text(' ', strip=True):
            nxt = h.find_next_sibling()
            text = (nxt.get_text(' ',strip=True) if isinstance(nxt,Tag) else '')
            if any(x in text for x in ['無法可靠', '不放', '沒有可精準', '無可靠', 'Targeted Screenshot']):
                if nxt: nxt.decompose()
                h.decompose()


def inject_file(path, asset_prefix, historical=False):
    html = path.read_text('utf-8')
    soup = BeautifulSoup(html, 'html.parser')
    changed = False
    for article in soup.find_all('article'):
        title_tag = article.find(['h2','h3','h4'])
        if not title_tag: continue
        case = matching_case(title_tag.get_text(' ', strip=True))
        if not case: continue
        if article.find('figure', class_='case-preview'):
            continue
        summary = article.find('p', class_='summary')
        if not summary:
            # TOP cards sometimes use a plain first paragraph.
            summary = title_tag.find_next('p')
            if summary and summary.find_parent('article') != article: summary = None
        target = summary or title_tag
        target.insert_after(make_preview(soup, case, asset_prefix))
        remove_no_image_note(article)
        changed = True
    if changed:
        # BeautifulSoup serialization is acceptable for this static site and keeps content intact.
        path.write_text(str(soup), 'utf-8')
    return changed


def append_css(path):
    text = path.read_text('utf-8')
    if 'Visual Evidence Preview: local assets generated' not in text:
        path.write_text(text.rstrip()+PREVIEW_CSS, 'utf-8')
        return True
    return False


def bump_cache(path):
    text = path.read_text('utf-8')
    old = text
    text = text.replace('styles.css?v=20260822-3','styles.css?v=20260822-4')
    text = text.replace('home-content.css?v=20260822-3','home-content.css?v=20260822-4')
    text = text.replace('../styles.css"','../styles.css?v=20260822-4"')
    if text != old:
        path.write_text(text,'utf-8')
        return True
    return False


def main():
    changed=[]
    home = ROOT/'index.html'
    hist = ROOT/'2026-08-22'/'index.html'
    if inject_file(home, 'assets/visual/'): changed.append(str(home.relative_to(ROOT)))
    if hist.exists() and inject_file(hist, '../assets/visual/', historical=True): changed.append(str(hist.relative_to(ROOT)))
    if append_css(ROOT/'home-content.css'): changed.append('home-content.css')
    if append_css(ROOT/'styles.css'): changed.append('styles.css')
    if bump_cache(home): changed.append('index.html(cache)')
    if hist.exists() and bump_cache(hist): changed.append('2026-08-22/index.html(cache)')
    print('preview injection changed:', ', '.join(changed) if changed else 'nothing')

if __name__ == '__main__': main()
