#!/usr/bin/env python3
import json, re
from pathlib import Path
from bs4 import BeautifulSoup, Tag

ROOT=Path(__file__).resolve().parents[1]
CFG=json.loads((ROOT/'visual-assets.json').read_text('utf-8'))
CASES=[]
for e in CFG.get('entries',[]):
    CASES.append({'keys':e.get('title_keys') or e.get('keywords') or [e['id']], 'asset':f"{e['id']}.jpg", 'label':e.get('label','SOURCE COVER'), 'source':e['page_url']})

PREVIEW_CSS='''\n/* Visual Evidence Preview: local assets generated by scripts/extract_visual_assets.py */\n.case-preview{margin:12px 0 4px;max-width:760px}.case-preview a{display:block;text-decoration:none}.case-preview img{display:block;width:100%;height:auto;max-height:430px;object-fit:contain;border-radius:10px;border:1px solid #29384f;background:#0b1220}.case-preview figcaption{margin-top:6px;color:#8793a8;font-size:.66rem;font-weight:900;letter-spacing:.06em}.case-preview figcaption span{color:#a69cff}.news .case-preview img,.category-news .case-preview img{border-color:#dde2e9;background:#f5f7fa}.news .case-preview figcaption,.category-news .case-preview figcaption{color:#717b89}.news .case-preview figcaption span,.category-news .case-preview figcaption span{color:#6359c9}@media(max-width:760px){.case-preview img{max-height:360px}}\n'''

def latest_daily_page():
    dirs=[]
    for p in ROOT.iterdir():
        if p.is_dir() and re.fullmatch(r'20\d{2}-\d{2}-\d{2}',p.name) and (p/'index.html').exists(): dirs.append(p)
    return (max(dirs,key=lambda p:p.name)/'index.html') if dirs else None

def matching_case(text):
    low=text.lower()
    for case in CASES:
        if any(str(k).lower() in low for k in case['keys']): return case
    return None

def make_preview(soup,case,prefix):
    fig=soup.new_tag('figure',attrs={'class':'case-preview','data-visual-id':case['asset'].rsplit('.',1)[0]})
    a=soup.new_tag('a',href=case['source'],target='_blank',rel='noreferrer',title='開啟原始案例')
    img=soup.new_tag('img',src=f'{prefix}{case["asset"]}',alt=f'{case["label"]} preview',loading='lazy',decoding='async')
    img['onerror']="this.closest('.case-preview').style.display='none'"; a.append(img); fig.append(a)
    cap=soup.new_tag('figcaption'); tag=soup.new_tag('span'); tag.string=case['label']; cap.append(tag); cap.append(' · Local visual evidence · 點圖開啟原始來源'); fig.append(cap)
    return fig

def remove_no_image_note(article):
    changed=False; stale=['無法可靠','不放替代圖','不放整頁','沒有通過 QA','沒有可精準','無可靠','Targeted Screenshot','目前沒有通過']
    for p in list(article.find_all('p')):
        txt=p.get_text(' ',strip=True)
        if 'Visual Evidence' in txt and any(x in txt for x in stale): p.decompose(); changed=True
    for h in list(article.find_all('h4')):
        if 'Visual Evidence' in h.get_text(' ',strip=True):
            nxt=h.find_next_sibling(); txt=nxt.get_text(' ',strip=True) if isinstance(nxt,Tag) else ''
            if any(x in txt for x in stale):
                if nxt: nxt.decompose()
                h.decompose(); changed=True
    return changed

def inject_file(path,prefix):
    soup=BeautifulSoup(path.read_text('utf-8'),'html.parser'); changed=False
    for article in soup.find_all('article'):
        title=article.find(['h2','h3','h4'])
        if not title: continue
        case=matching_case(title.get_text(' ',strip=True))
        if not case: continue
        if remove_no_image_note(article): changed=True
        existing=article.find('figure',class_='case-preview')
        if existing:
            img=existing.find('img'); cap=existing.find('figcaption')
            expected=f'{prefix}{case["asset"]}'
            if img and img.get('src')!=expected: img['src']=expected; changed=True
            if cap and cap.find('span') and cap.find('span').get_text(strip=True)!=case['label']: cap.find('span').string=case['label']; changed=True
            continue
        summary=article.find('p',class_='summary')
        if not summary:
            summary=title.find_next('p')
            if summary and summary.find_parent('article')!=article: summary=None
        (summary or title).insert_after(make_preview(soup,case,prefix)); changed=True
    if changed: path.write_text(str(soup),'utf-8')
    return changed

def append_css(path):
    text=path.read_text('utf-8')
    if 'Visual Evidence Preview: local assets generated' not in text: path.write_text(text.rstrip()+PREVIEW_CSS,'utf-8'); return True
    return False

def main():
    changed=[]; home=ROOT/'index.html'; hist=latest_daily_page()
    if inject_file(home,'assets/visual/'): changed.append('index.html')
    if hist and inject_file(hist,'../assets/visual/'): changed.append(str(hist.relative_to(ROOT)))
    css_changed=False
    for css in [ROOT/'home-content.css',ROOT/'styles.css']:
        if append_css(css): changed.append(css.name); css_changed=True
    # Existing cache-bust is retained; only first installation needed to bump it.
    if css_changed:
        text=home.read_text('utf-8').replace('styles.css?v=20260822-3','styles.css?v=20260822-4').replace('home-content.css?v=20260822-3','home-content.css?v=20260822-4')
        home.write_text(text,'utf-8')
        if hist:
            t=hist.read_text('utf-8')
            if '../styles.css"' in t: hist.write_text(t.replace('../styles.css"','../styles.css?v=20260822-4"'),'utf-8')
    print('preview injection changed:',', '.join(changed) if changed else 'nothing')

if __name__=='__main__': main()
